name: omni_connectivity
description: "Lightweight reachability/probe checker for Flutter (native + web) that supports all the protocol you knows."
version: 0.0.1
homepage: https://github.com/sumitsharansatsangi/omni_connectivity
repository: https://github.com/sumitsharansatsangi/omni_connectivity
issue_tracker: https://github.com/sumitsharansatsangi/omni_connectivity/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  # Flutter versions prior to 3.7 did not support because on the dependency on `connectivity_plus`.
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0   
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
